openapi: 3.0.3
info:
  title: API de Reportes
  version: 1.1.0
  description: API para recibir, servir y borrar reportes con coordenadas, fecha e imagen.

paths:
  /reportes:
    post:
      summary: Crear un nuevo reporte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat:
                  type: number
                  format: float
                  example: 14.004107
                lon:
                  type: number
                  format: float
                  example: -74.806981
                fecha:
                  type: string
                  format: date-time
                  example: "2025-10-10T14:48:00.000Z"
                foto_base64:
                  type: string
                  description: Imagen codificada en base64
                  example: "iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAIAAACRXR/mAAA..."
              required:
                - lat
                - lon
                - fecha
                - foto_base64
      responses:
        '201':
          description: Reporte creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: "Reporte recibido con éxito"
        '400':
          description: Solicitud inválida

    get:
      summary: Obtener todos los reportes
      responses:
        '200':
          description: Lista de reportes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    lat:
                      type: number
                      format: float
                    lon:
                      type: number
                      format: float
                    fecha:
                      type: string
                      format: date-time
                    foto_base64:
                      type: string

  /borrar_todos:
    delete:
      summary: Borrar todos los reportes
      responses:
        '200':
          description: Confirmación de borrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: "Todos los reportes han sido eliminados"
        '500':
          description: Error interno del servidor
